
output "host_catalog" {
  value = boundary_host_catalog_plugin.host_catalog.id
}

# The scope of the org we are using
# really need to re-do this to be generated by TF in the first place
output "org_scope"{
   value=var.se_org_scope
}

output "demo-project-id"{
  value=boundary_scope.project.id
}

#export this so that other workspaces don't have to keep this variable 
#lying around everywhere
output "tf-workspace-pwd"{
  sensitive=true
  value = var.TF_WORKSPACE_PWD
}
