
output "host_catalog" {
  value = boundary_host_catalog_plugin.host_catalog.id
}

# The scope of the org we are using
# really need to re-do this to be generated by TF in the first place
output "org_scope"{
   value=var.se_demo_scope
}
